### ISSUE TITLE
How to create logins with different models

### ISSUE THREAD

**Issue by dagume** [joselfonseca/lighthouse-graphql-passport-auth#26] opened 2019-09-11 23:37 UTC
Hi Jose, I want to be able to authenticate with the `Contact` model instead of` User` where I can make this change and what should I take into account when making that change?

**Comment by joselfonseca** [comment] 2019-09-17 23:15
Yes, that should work fine. As long as you are pointing the schema to the right file and the resolver returns the data the type needs it should work. If you run into any issues would be good to let us know in this thread because is actually a good use case and we have not tested as we haven´t had any use case like this. As long as that model works for authentication you should be good.

**Comment by joselfonseca** [comment] 2019-09-17 23:17
Maybe update this as well

https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/src/GraphQL/Mutations/Login.php#L24

**Comment by joselfonseca** [comment] 2019-09-17 23:18
As well as this

https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/src/GraphQL/Mutations/Register.php#L31

**Comment by DaveDamage** [comment] 2019-09-19 13:16
I tried the Approach and get an error when I try to login, apparently either Login or the MakeRequest don't like the change:

`{
  "errors": [
    {
      "message": "An unknown error occurred.",
      "extensions": {
        "guards": [],
        "category": "authentication"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ],
      "trace": [
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/joselfonseca/lighthouse-graphql-passport-auth/src/GraphQL/Mutations/Login.php",
          "line": 21,
          "call": "Joselfonseca\\LighthouseGraphQLPassport\\GraphQL\\Mutations\\BaseAuthResolver::makeRequest(array(5))"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/nuwave/lighthouse/src/Schema/Directives/FieldDirective.php",
          "line": 68,
          "call": "Joselfonseca\\LighthouseGraphQLPassport\\GraphQL\\Mutations\\Login::resolve(null, array(3), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/nuwave/lighthouse/src/Schema/Factories/FieldFactory.php",
          "line": 225,
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\FieldDirective::Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(null, array(2), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 632,
          "call": "Nuwave\\Lighthouse\\Schema\\Factories\\FieldFactory::Nuwave\\Lighthouse\\Schema\\Factories\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 555,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveOrError(instance of GraphQL\\Type\\Definition\\FieldDefinition, instance of GraphQL\\Language\\AST\\FieldNode, instance of Closure, null, instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 478,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveField(GraphQLType: Mutation, null, instance of ArrayObject(1), array(1))"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 921,
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(array(0), 'login')"
        },
        {
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(array(0), 'login')"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 923,
          "function": "array_reduce(array(1), instance of Closure, array(0))"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 494,
          "call": "GraphQL\\Executor\\ReferenceExecutor::promiseReduce(array(1), instance of Closure, array(0))"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 256,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeFieldsSerially(GraphQLType: Mutation, null, array(0), instance of ArrayObject(1))"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 208,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeOperation(instance of GraphQL\\Language\\AST\\OperationDefinitionNode, null)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/webonyx/graphql-php/src/Executor/Executor.php",
          "line": 155,
          "call": "GraphQL\\Executor\\ReferenceExecutor::doExecute()"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/webonyx/graphql-php/src/GraphQL.php",
          "line": 158,
          "call": "GraphQL\\Executor\\Executor::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, instance of GraphQL\\Language\\AST\\DocumentNode, null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/webonyx/graphql-php/src/GraphQL.php",
          "line": 90,
          "call": "GraphQL\\GraphQL::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, 'mutation {\n  login(input: {username: \"davidbecker81@gmail.com\", password: \"Imi7.Hs!\"}) {\n    access_token\n    refresh_token\n    expires_in\n    token_type\n  }\n}', null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null, array(29))"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/nuwave/lighthouse/src/GraphQL.php",
          "line": 177,
          "call": "GraphQL\\GraphQL::executeQuery(instance of GraphQL\\Type\\Schema, 'mutation {\n  login(input: {username: \"davidbecker81@gmail.com\", password: \"Imi7.Hs!\"}) {\n    access_token\n    refresh_token\n    expires_in\n    token_type\n  }\n}', null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null, array(29))"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/nuwave/lighthouse/src/GraphQL.php",
          "line": 116,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeQuery('mutation {\n  login(input: {username: \"davidbecker81@gmail.com\", password: \"Imi7.Hs!\"}) {\n    access_token\n    refresh_token\n    expires_in\n    token_type\n  }\n}', instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php",
          "line": 70,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeRequest(instance of Nuwave\\Lighthouse\\Execution\\LighthouseRequest)"
        },
        {
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController::query(instance of Nuwave\\Lighthouse\\Execution\\LighthouseRequest)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
          "line": 54,
          "function": "call_user_func_array(array(2), array(1))"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
          "line": 45,
          "call": "Illuminate\\Routing\\Controller::callAction('query', array(1))"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
          "line": 219,
          "call": "Illuminate\\Routing\\ControllerDispatcher::dispatch(instance of Illuminate\\Routing\\Route, instance of Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController, 'query')"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
          "line": 176,
          "call": "Illuminate\\Routing\\Route::runController()"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 680,
          "call": "Illuminate\\Routing\\Route::run()"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 30,
          "call": "Illuminate\\Routing\\Router::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/nuwave/lighthouse/src/Support/Http/Middleware/AcceptJson.php",
          "line": 30,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 163,
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AcceptJson::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 104,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 682,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 657,
          "call": "Illuminate\\Routing\\Router::runRouteWithinStack(instance of Illuminate\\Routing\\Route, instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 623,
          "call": "Illuminate\\Routing\\Router::runRoute(instance of Illuminate\\Http\\Request, instance of Illuminate\\Routing\\Route)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 612,
          "call": "Illuminate\\Routing\\Router::dispatchToRoute(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 176,
          "call": "Illuminate\\Routing\\Router::dispatch(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 30,
          "call": "Illuminate\\Foundation\\Http\\Kernel::Illuminate\\Foundation\\Http\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/app/Http/Middleware/Cors.php",
          "line": 18,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 163,
          "call": "App\\Http\\Middleware\\Cors::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/app/Http/Middleware/Locale.php",
          "line": 35,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 163,
          "call": "App\\Http\\Middleware\\Locale::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/fideloper/proxy/src/TrustProxies.php",
          "line": 57,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 163,
          "call": "Fideloper\\Proxy\\TrustProxies::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
          "line": 21,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 163,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
          "line": 21,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 163,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
          "line": 27,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 163,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
          "line": 62,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 163,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 104,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 151,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 116,
          "call": "Illuminate\\Foundation\\Http\\Kernel::sendRequestThroughRouter(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/Webprojects/gb-shop/public/index.php",
          "line": 55,
          "call": "Illuminate\\Foundation\\Http\\Kernel::handle(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/Users/davidbecker/.composer/vendor/laravel/valet/server.php",
          "line": 158,
          "function": "require('/Users/davidbecker/Webprojects/gb-shop/public/index.php')"
        }
      ]
    }
  ]
}`

**Comment by joselfonseca** [comment] 2019-10-01 19:36
Anyone here got this working? if not I will give it a try in an empty project to see if this is supported or not.

**Comment by suonsamoun** [comment] 2019-12-04 16:01
### ### ### ### ### ### ### ### ### ### 

> 

> 

> [****]([url]([url](

- 

- [ ] @1. url

)))

**Comment by kevinpallado** [comment] 2019-12-19 13:12
Any update on this one?

**Comment by generator85** [comment] 2020-02-16 16:57
Love to see a fix for this as well.

**Comment by joselfonseca** [comment] 2020-03-13 01:57
So I was actually able to do this without any modifications to the package and just updating something simple in the configuration and the login mutation.

<img width="1680" alt="Screen Shot 2020-03-12 at 8 52 54 PM" src="https://user-images.githubusercontent.com/2046653/76582317-eacd6e80-64a3-11ea-947c-a46ab954d1c9.png">

I have uploaded the demo here https://github.com/joselfonseca/lightouse-other-model-auth

**Comment by joselfonseca** [comment] 2020-03-13 01:58
I will document how to do this soon.

**Closed by joselfonseca** 2020-03-13 01:57 UTC
Labels: question

**Comment by glupeksha** [comment] 2021-06-02 15:25
@joselfonseca The problem is that resolver automatically select the model in auth.providers.users.model. If we can choose which provider to be used, it would be really really helpful.
